# Nome do site
site_name:  üìä Projeto DBT + Faker + PostgreSQL

# URL do site (opcional)
site_url: "https://prog-lucasalves.github.io/AED_DBT/"

# Tema do site
theme:
  name: 'material'
  language: 'pt-BR'
  palette:
    primary: 'indigo'
    accent: 'pink'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  logo: 'image/logo.png'

# Navega√ß√£o
nav:
  - Home: index.md
  - dbt Core:
      - Introdu√ß√£o: 'dbt/intro.md'
  - SQLAlchemy:
      - Introdu√ß√£o: 'sqlalchemy/intro.md'


# Plugins (opcional)
plugins:
  - search  # Habilita pesquisa

# Configura√ß√µes adicionais (opcional)
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Prog-LucasAlves/AED_DBT

# Configura√ß√µes para Markdown
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
